radixdlt/sargon

.github/workflows/release-android.yml
.github/workflows/release-desktop-bins.yml

Android and desktop binaries were not being built as they were expecting a tag to be created. For now CD workflows will start on each develop push

Create maven deployment on each push on develop

---

apple/Sources/Sargon/Extensions/Methods/RET/TransactionManifest+Wrap+Functions.swift
apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
apple/Tests/TestCases/RET/TransactionManifestTests.swift
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/TransactionManifest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/TransactionManifestTest.kt
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/mod.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest_uniffi_fn.rs

Exposed 3 uniffi methods on TransactionManifest and created extensions for them in swift/kotlin
* for instructions
* for network id
* for blobs
Specifically for swift, I removed the `description` for TransactionManifest, since a Manifest cannot be described only with instructions and I replaced all usages with `instructionsString`.

Create extensions for TransactionManifest

---

apple/Sources/Sargon/Extensions/Methods/Prelude/Decimal192+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Methods/Prelude/NonFungibleGlobalID+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Methods/Prelude/NonFungibleLocalID+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/Address+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Prelude/Decimal192+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Prelude/NonFungibleGlobalID+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Prelude/NonFungibleLocalID+Swiftified.swift
apple/Sources/Sargon/Protocols/AddressProtocol.swift
apple/Sources/Sargon/Protocols/IdentifiableByStringProtocol.swift
apple/Tests/TestCases/Address/AccountAddressTests.swift
apple/Tests/TestCases/Prelude/Decimal192Tests.swift
apple/Tests/TestCases/Prelude/NonFungibleGlobalIDTests.swift
apple/Tests/TestCases/Prelude/NonFungibleLocalIDTests.swift
apple/Tests/Utils/AddressProtocolTests.swift
apple/Tests/Utils/IdentifiableByStringProtocolTests.swift
apple/Tests/Utils/SargonModelProtocol.swift

Swift only:
* move Codable impl of `Decimal192`, all addresses and `NonFungible`IDs into Sargon, needed by iOS wallet due to CacheClient 
* add casting methods on Address
* add `asDouble` which seems it cannot fail, so made into computed property. Should be moved into Rust Sargon...

Codable Addresses, Decimal192, NonFunIDs

---

jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/IntentHash.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/SignedIntentHash.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/IntentHashTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/SignedIntentHashTest.kt
src/wrapped_radix_engine_toolkit/low_level/transaction_hashes/transaction_hashes.rs

* Method added in src and uniffi exports
* Required for https://github.com/radixdlt/babylon-wallet-ios/pull/1070#discussion_r1549116709

Implement Intent/SignedIntent Hash formatted method

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Swiftified/Address/AccessControllerAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/AccountAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/Address+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/AddressOfAccountOrPersona+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/ComponentAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/IdentityAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/NonFungibleResourceAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/PackageAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/PoolAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/ResourceAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/ValidatorAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Address/VaultAddress+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Derivation/AccountPath+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Derivation/CAP26Path+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Derivation/IdentityPath+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Keys/Ed25519PublicKey+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Keys/PublicKey+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Keys/Secp256k1PublicKey+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Prelude/NonFungibleGlobalID+Swiftified.swift
apple/Sources/Sargon/Protocols/AddressProtocol.swift
apple/Sources/Sargon/Protocols/CAP26PathProtocol.swift
apple/Sources/Sargon/Protocols/PublicKeyProtocol.swift
apple/Tests/TestCases/Address/AccountAddressTests.swift
apple/Tests/TestCases/Crypto/PublicKeyTests.swift
apple/Tests/TestCases/Prelude/NonFungibleGlobalIDTests.swift
apple/Tests/Utils/AddressProtocolTests.swift

Rename method on *specific* Addresses which was name ~func embed()~ -> `var asGeneral` (a computed property)
Rename method ~`func into()`~ on `Address` -> `func asSpecific()`

Rename into() -> asSpecific and embed() -> asGeneral

---

Cargo.lock
Cargo.toml
_typos.toml
src/core/types/decimal192.rs
src/core/types/keys/ed25519/private_key.rs
src/core/types/keys/is_private_key.rs
src/core/types/keys/private_key.rs
src/core/types/keys/secp256k1/private_key.rs
src/core/types/keys/secp256k1/public_key.rs
src/core/utils/string_utils.rs
src/hierarchical_deterministic/bip32/hd_path.rs
src/hierarchical_deterministic/bip32/hd_path_component.rs
src/hierarchical_deterministic/derivation/mnemonic_with_passphrase.rs
src/wrapped_radix_engine_toolkit/low_level/compiled_notarized_intent.rs
src/wrapped_radix_engine_toolkit/low_level/notarized_transaction.rs
src/wrapped_radix_engine_toolkit/low_level/signed_intent.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_intent.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/instructions/instructions.rs

Remove `slip10` crate by random dude => replaced with IOTA's which can be deemed trustworthy => which also implements Secp256k1 SLIP10! So we can then also remove `bip32` crate
Add `k256` (already added, as transitive dependency!) explicitly, so that we can crate Secp256k1PublicKey from uncompressed bytes.
This was the "hard part" of the work of making Sargon production ready viz. pinning Dependencies in Cargo.toml. A trivial follow up PR will be made tommorrow pinning the rest.

New slip10 crate

---

Cargo.lock
Cargo.toml
scripts/ios/build-sargon.sh
src/core/types/keys/ed25519/public_key.rs

Continue "pinning" crates by usage of explicit commit hashes (`rev`) - soon all crates have been pinned.
These crates was removed all together:
- ed25519-dalek (the Ed25519PublicKey uses Ed25519 inside of IOTA Crypto crate)
- nutype
- schemars

Pin Crates: Batch 2

---

jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Profile.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ProfileTest.kt
src/profile/v100/profile.rs
src/profile/v100/profile_uniffi_fn.rs
src/wallet/wallet.rs
src/wallet/wallet_accounts.rs

* Removed the `PrivateHierarchicalDeterministicFactorSource` as a parameter in Profile initialization and replaced it with just the `DeviceFactorSource`

Avoid passing mnemonic in ffi

---

src/core/error/common_error.rs
src/core/types/keys/slip10_curve.rs
src/profile/v100/app_preferences/gateways/gateway.rs
src/profile/v100/app_preferences/gateways/gateways.rs
src/profile/v100/factors/factor_source_crypto_parameters.rs
src/profile/v100/factors/factor_sources/factor_sources.rs
src/profile/v100/identified_elements.rs
src/profile/v100/networks/network/accounts.rs
src/profile/v100/networks/network/authorized_dapps.rs
src/profile/v100/networks/network/personas.rs
src/profile/v100/networks/network/profile_network.rs
src/profile/v100/networks/profile_networks.rs

* Identified array of `[SLIP10Curve]` can now be referred to as `SLIP10Curves`
* `other: IdentifiedVecVia<Gateway>` is now called as `OtherGateways`. Could not refer to it as `Gateways` since Gateways is another struct with current inside. So I had to change the `decl_...` api a bit.
* The `impl` methods has a small renaming. For structs like `SLIP10Curve` the method that was creating the struct with just one curve would be named `with_s_l_i_p_10_curve()`. IMHO the name `just` for a method that instantiates an array with just one element inside was easier to remember. Also I just kept `from_iter` instead of redefining another method since it was doing the same thing.

Create SupportedCurves and OtherGateways through macro

---

apple/Sources/Sargon/Extensions/Methods/Crypto/Derivation/Mnemonic+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Methods/Crypto/Derivation/MnemonicWithPassphrase+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/SampleValues/Crypto/Keys/HierarchicalDeterministicPublicKey+SampleValues.swift
apple/Sources/Sargon/Extensions/Swiftified/Crypto/Keys/HierarchicalDeterministicPublicKey+Swiftified.swift
apple/Tests/TestCases/Crypto/HierarchicalDeterministicPublicKeyTests.swift
apple/Tests/TestCases/Crypto/MnemonicWithPassphraseTests.swift
src/hierarchical_deterministic/derivation/hierarchical_deterministic_public_key_uniffi_fn.rs
src/hierarchical_deterministic/derivation/mnemonic_with_passphrase.rs
src/hierarchical_deterministic/derivation/mnemonic_with_passphrase_uniffi_fn.rs
src/hierarchical_deterministic/derivation/mod.rs

Add a new method on `MnemoncWithPassphrase` to validate HD public keys, this is step 1/3 to try to avoid UniFFI exporting `to_seed` method on `MnemoncWithPassphrase`, all three being:
1) derive new public key
2) validate keys (actually using the above...)
3) signing - we will be able to do `mnemonicWithPass.sign(derivationPath, hash)` in Swift and Kotlin, calling that UF expose function in Sargon, which will allows us to not UF export `to_seed`. 
Will follow up with signing later...
Add `sample` and `sampleOther` on HD PubKeys, and swiftify the new `validate` method.

Validation public keys

---

apple/Tests/TestCases/Address/AccountAddressTests.swift
apple/Tests/TestCases/Address/LegacyOlympiaAccountAddressTests.swift
src/profile/v100/address/account_address.rs
src/profile/v100/address/address_format.rs
src/profile/v100/address/legacy_olympia_account_address.rs
src/profile/v100/address/non_fungible_global_id.rs
src/profile/v100/address/non_fungible_local_id.rs
src/profile/v100/address/resource_address.rs
src/profile/v100/address/wrap_ret_address.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_hashes/transaction_hashes.rs

The wallet apps will need to colorise the part of an address that is normally hidden. The new `AddressFormat::Middle` will return such part of a given address.
[ABW-3212](https://radixdlt.atlassian.net/browse/ABW-3212)
[ABW-3212]: https://radixdlt.atlassian.net/browse/ABW-3212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add AddressFormat.Middle support

---

Cargo.lock
Cargo.toml
src/core/types/keys/public_key.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/instructions/instructions.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/instructions/instructions_secret_magic.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest.rs

Bump Scrypto to 1.1.2 which contains the two fixes to Rust Analyzer:
* https://github.com/radixdlt/radixdlt-scrypto/pull/1781
* https://github.com/radixdlt/radixdlt-scrypto/pull/1779
Also bump RET to 2.0.1 which uses Scrypto 1.1.2
* Bump Sargon to 0.7.1 (and have manually tagged and pushed 0.7.0 tag so that next release will be 0.7.1)

Sargon 0.7.1 | Rust Analyzer is FAST again, thx to bumping Scrypto (and RET)

---

.github/workflows/release-desktop-bins.yml
.github/workflows/release.yml
.github/workflows/test.yml
apple/Tests/TestCases/Prelude/DependencyInformationTests.swift
jvm/sargon-android/src/test/java/com/radixdlt/sargon/DependencyInformationTest.kt
scripts/ios/release.sh
src/wrapped_radix_engine_toolkit/high_level/sargon_specific_types/build_information/dependency_information.rs
src/wrapped_radix_engine_toolkit/high_level/sargon_specific_types/build_information/dependency_information_uniffi_fn.rs

I've also changed the default branch to be `main` (and changes the branch protection rules to use `main`)

update CI / CD to use main branch instead of develop

---

Cargo.lock
Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Accounts.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/AssetsExceptionList.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/AuthorizedDapps.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/DepositorsAllowList.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/EntityFlags.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/FactorSources.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Gateways.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/IdentifiedArray.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/P2PLinks.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Personas.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/ProfileNetworks.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/ReferencesToAuthorizedPersonas.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/SupportedCurves.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/AccountsTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/AssetsExceptionListTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/AuthorizedDappsTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/DepositorsAllowListTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/EntityFlagsTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/FactorSourcesTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/GatewaysTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/IdentifiedArrayTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/P2PLinksTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/PersonasTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ProfileNetworksTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ReferencesToAuthorizedPersonasTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/SupportedCurvesTest.kt

* `equals`, `hashCode` and `toString` need to be exposed in interface so the actual class can use those methods when delegating to `array` instead of the default implementations on `Any`
* Individual tests for each collection
* Added `operator fun contains` so we can use `in` operator in project
* Inner `array` should become property so equality could work with delegation. Not sure if it was possible without making `array` property of the class.
* There is a false positive in code coverage regarding `javaClass` check, so I had to ignore the whole method, even though it is tested.

Fix equality and hashcode in identifiable collections

---

.github/workflows/release-android.yml
.github/workflows/release-desktop-bins.yml
jvm/buildSrc/build.gradle.kts
jvm/buildSrc/src/main/java/com/radixdlt/cargo/toml/SargonVersion.kt
jvm/sargon-android/build.gradle.kts
jvm/sargon-desktop-release/build.gradle.kts

* Android and desktop-bins now use the `cargo.toml` version to decide on the version name in maven
* Falls back to latest git tag
* All can be calculated from inside gradle. No need to export env variables.

Use cargo.toml for determining version name

---

jvm/gradle/libs.versions.toml
jvm/sargon-android/build.gradle.kts
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Decimal192.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt

* Android keyboards may allow more characters than decimals to be typed regardless the current locale
* We need to act upon the text input and edit the string accordingly.
* Only digits and decimal separator is allowed.
* Any text is stripped from non-allowed characters with a regex and passes the result to sargon along with the locale's decimal separator.
* The same applies when the converted decimal192 is converted back to string for text inputs. Again only digits and decimal separator are allowed.
* Space is represented as 0. (In case user pastes `" "`)

Decimal192 string parsing and representing in text fields

---

Cargo.lock
Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Decimal192.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt

- wrap `decimal` property of `TextInputDecimal` in runCatching {} to catch decimal parse error
- add test examples for this particular case

Make TextInputDecimal decimal property nullable

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Methods/Profile/Profile+Wrap+Functions.swift
apple/Tests/TestCases/Profile/ProfileTests.swift
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Profile.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ProfileTest.kt
src/profile/encrypted/encryption/encrypted_profile_snapshot.rs
src/profile/v100/profile.rs
src/profile/v100/profile_uniffi_fn.rs
src/radix_connect/p2p_links/radix_connect_purpose.rs

Adds a new function that checks if an encrypted profile contains legacy P2P links.

[CAP-36] Add encrypted profile legacy P2P links check

---

Cargo.lock
Cargo.toml
Package.swift
apple/Sources/Sargon/Extensions/Methods/Profile/Profile+Wrap+Functions.swift
apple/Tests/TestCases/Profile/Collection/AccountsTests.swift
apple/Tests/TestCases/Profile/Collection/FactorSourcesTests.swift
apple/Tests/TestCases/Profile/Factor/DeviceFactorSourceTests.swift
apple/Tests/TestCases/Profile/ProfileTests.swift
apple/Tests/Utils/Test.swift
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Profile.kt
src/profile/v100/json_data_convertible.rs
src/profile/v100/profile.rs
src/profile/v100/profile_uniffi_fn.rs

I forgot that we perform 2's complement on **every single byte, byte by byte** in BagOfBytes, which is very costly for large data - such as Profile. Therefore, we SHOULD NOT use JSON Data for Profile API's - but rather JSON String. 
We get an immediate 10x speedup in Swift by doing so.
The `vector` is [the huge profile with 1000 accounts](https://github.com/radixdlt/sargon/blob/main/fixtures/vector/huge_profile_1000_accounts.json).
```swift
// Macbook Pro M2: 0.64 seconds
func test_performance_json_encoding_data() throws {
let (sut, _) = vector
measure {
let _ = sut.jsonData()
}
}
// Macbook Pro M2: 0.06 (10x speedup vs BagOfBytes)
func test_performance_json_encoding_string() throws {
let (sut, _) = vector
measure {
let _ = sut.jsonString(prettyPrint: false)
}
}
// Macbook Pro M2: 0.26 …
```

Use String for JSON coding of Profile (10x speedup)

---

Cargo.lock
Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/MnemonicWithPassphrase.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/MnemonicWithPassphraseTest.kt

It looks like there was a typo in current sargon jvm for backwards compatible android mnemonic.

Fix android mnemonic  serialization

---

Cargo.lock
Cargo.toml
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/transaction_manifest.rs

Bump `RET` to a version where the non sensical manifest does not crash when calling `summary` on it.
```text
CALL_METHOD
Address("account_tdx_2_1c90qdw5e3t3tjyd8axt3zg9zezhhhymt2mr8y4l0k2285mfwhczhdt")
"withdraw"
Address("account_tdx_2_12y0errvzu4caktegxc5v0ug93u5yat9d90k4zdqkcy6n55pt7wlgmq")
Decimal("0.01")
;
TAKE_FROM_WORKTOP
Address("resource_tdx_2_1thqru9whuem5sjltshg4q7vj3e22xfh27u6s9xvwecz4fallqjny90")
Decimal("0.01")
Bucket("burn")
;
BURN_RESOURCE
Bucket("burn")
;
```
The above nonsensical manifest crashed when we called `summary` on it, but not now after bumping RET.

Throw err for invalid manifest instead of crash in summary

---

Cargo.lock
Cargo.toml
apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
jvm/sargon-android/src/test/java/com/radixdlt/sargon/TransactionManifestTest.kt
src/wrapped_radix_engine_toolkit/high_level/manifest_building/modify_manifest.rs
src/wrapped_radix_engine_toolkit/high_level/ret_api.rs
src/wrapped_radix_engine_toolkit/high_level/sargon_specific_types/transaction_guarantee.rs

The `TransactionGuarantee` holds the `amount` that we guarantee as minimum for a transaction. Such value is calculated from the `total` * `percentage`, where the latter comes from user default preferences or a specific value selected for this transaction. 
After a `TransactionGuarantee` has been saved, user could want to edit the percentage selected. Up until now, this value was shown by doing the reverse calculation (`percentage` = `amount` / `total`). However, this would lead to different values than the original user input on certain cases. 
For example, let's say we have a transaction of `20 CANDY`, an asset that has 0 divisibility. If the user sets a percentage of `92%`, the `amount` will be set to `18` (since 18.4 isn't possible for this asset). However, if the user opens the view …

Add percentage to TransactionGuarantee 

---

Cargo.lock
Cargo.toml
src/wrapped_radix_engine_toolkit/high_level/manifest_building/third_party_deposit_update/manifest_third_party_deposit_update.rs
src/wrapped_radix_engine_toolkit/high_level/manifest_building/third_party_deposit_update/third_party_deposits_delta.rs

Fix bug present in Production, user is unable to update Third Party Deposit settings by removing `depositor`. 
This fixes that.

fix third party deposit manifest

---

Cargo.lock
Cargo.toml

something got messed up with sargon release versions. main branch has 1.0.4 version in toml, but last release tag is 1.0.5 and last merge to main did not result in an iOS release....

just bump to 1.0.6

---

Cargo.lock
Cargo.toml
jvm/sargon-android/build.gradle.kts

This is an attempt to improve consecutive builds time by adding `regenerate` boolean argument to build gradle tasks. If you don't pass any arg to the gradle task, it will follow the same steps as before (generating uniffi bindings which takes long and re-run even if there are no changes in rust), but if passing `regenerate=false` to gradle task, it skips this step entirely and rely upon previously generated bindings:
`./jvm/gradlew -p jvm/sargon-android testDebugUnitTest -Pregenerate=false`

Add 'regenerate' argument to build and test gradle tasks 

---

Cargo.lock
Cargo.toml
jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt
src/core/types/decimal192.rs
src/core/types/decimal192_uniffi_fn.rs

Update `Decimal192` parsing to truncate the fractional part to 18 decimals when parsing into the `ScryptoDecimal192` fails with the specific `ParseDecimalError::MoreThanEighteenDecimalPlaces`.

Truncate Decimal192 fractional part when it has more than 18 decimals

---

jvm/gradle/libs.versions.toml
jvm/sargon-android/build.gradle.kts
jvm/sargon-android/src/androidTest/kotlin/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorageTest.kt
jvm/sargon-android/src/androidTest/kotlin/com/radixdlt/sargon/os/storage/EncryptionHelperWithSpecKeyTest.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/Result.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorage.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/EncryptedPreferencesStorage.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/EncryptionHelper.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/KeySpec.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/Decimal192Test.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ResultTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/radixconnect/RadixConnectSessionStorageTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/EncryptedPreferencesStorageTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/EncryptionHelperWithEncryptionKeyTest.kt

In order to implement such "secure" storage I had to introduce to sargon some logic that existed in Android wallet.
* Some `Result` extensions were needed. Unit tested and made public to replace the ones we have in android wallet.
* `KeySpec` reintroduced. Temporarily became `internal` in order to not introduce a duplicate type to the existing one, but rather lie the foundation for all kinds of secure storages to be implemented when SargonOS will be integrated. * * The only class that is public for construction from wallet host will be `RadixConnectSessionStorage(context: Context)`. The host should instantiate this as a singleton using Hilt.
* Unit tests are difficult when you combine code with methods that exist on Android. Tried to unit test everything. `EncryptionHelper ` can encrypt …

Implement RadixConnectSessionStorage for kotlin

---

jvm/sargon-android/src/main/java/com/radixdlt/sargon/antenna/SargonNetworkAntenna.kt

* `GET` requests cannot have a request body.
* We initiate a `GET` request when requesting a well-known file.
* In Sargon an empty array is initialised and passed down to kotlin.
* Kotlin side needs to check if `body` is empty, and if it is pass `null` to okHttp.
* Otherwise this error is thrown: `method GET must not have a request body.`
> [!NOTE]
> Target branch is not `main`

Optional request body for `GET` methods

---

Cargo.lock
Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/MnemonicWithPassphrase.kt
src/core/error/common_error.rs
src/core/error/common_error_map.rs
src/core/error/mod.rs
src/profile/v100/json_data_convertible.rs
src/profile/v100/profile.rs
src/profile/v100/profile_uniffi_fn.rs
src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_uniffi_fn.rs
src/wallet/secure_storage/wallet_client_storage.rs

`FailedToDeserializeJSONToValue` was missing meaningful information that hosts could log, in order to find out what the problem is when deserialising a value.
2 methods can be applied on each `Result<*, serde_json::Error>` that can extract all needed information about deserialisation for both strings and byte arrays.
The aim is to use the `message` in hosts to extract logs.

Pass serde message information to `FailedToDeserializeJSONToValue`

---

Cargo.lock
Cargo.toml
apple/Tests/TestCases/Prelude/DisplayNameTests.swift
src/core/error/common_error.rs
src/core/error/common_error_map.rs
src/core/utils/string_utils.rs
src/profile/v100/entity/display_name.rs

* User reported with profile that had display names with longer than 30 chars. This was resulting the deserialisation of the profile to return an error.
* The display names are now truncated.
* Question for @CyonAlexRDX: The `CommonError::InvalidDisplayNameTooLong` in now unused. I purposely did not delete it. Is it safe to remove it and fix the error codes of the rest of the following errors?
* Question to all. I used the [`truncate()`](https://doc.rust-lang.org/std/string/struct.String.html#method.truncate) function. This might panic if "new_len does not lie on a [char](https://doc.rust-lang.org/std/primitive.char.html) boundary." Can someone help with suggestions on how this might fail? Or even suggest a better function?

Truncate display names with longer than 30 chars

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Swiftified/RET/TransactionManifest+Swiftified.swift
apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
src/core/error/common_error.rs
src/wrapped_radix_engine_toolkit/high_level/manifest_building/modify_manifest.rs
src/wrapped_radix_engine_toolkit/high_level/ret_api.rs

Jira ticket: [ABW-3433](https://radixdlt.atlassian.net/browse/ABW-3433)
- Removes the check `guarantees.len() > self.instructions().len()`
- Propagates panics to Swift as thrown errors
[ABW-3433]: https://radixdlt.atlassian.net/browse/ABW-3433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ABW-3433] Fix Manifest Crash

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Swiftified/Prelude/SargonError+Swiftified.swift
apple/Tests/TestCases/Prelude/SargonErrorTests.swift
src/core/error/common_error.rs

Jira ticket: [ABW-3454](https://radixdlt.atlassian.net/browse/ABW-3454)
- Make `SargonError` conform to `LocalizedError` to ensure a proper `localizedDescription` is displayed in the iOS wallet.
- Added a new UniFFI export function `is_safe_to_show_error_message` for hosts to determine if the `error_message` can be displayed to users. For now, the only error we consider "safe" is `FailedToDeserializeJSONToValue`
[ABW-3454]: https://radixdlt.atlassian.net/browse/ABW-3454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ABW-3454] iOS - Display proper error messages for Sargon errors

---

Cargo.lock
Cargo.toml
apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
fixtures/transaction/create_3_nft_collections.rtm
src/wrapped_radix_engine_toolkit/high_level/manifest_building/manifests_create_tokens.rs
src/wrapped_radix_engine_toolkit/high_level/token_definition_metadata.rs

When creating a test token, the manifest will now include metadata values for every accepted type.

Add some extra metadata fields when creating token

---

Cargo.lock
Cargo.toml
apple/Tests/TestCases/RET/ManifestBuilding/ManifestBuildingTests.swift
fixtures/transaction/create_3_nft_collections.rtm
src/profile/v100/address/resource_address.rs
src/wrapped_radix_engine_toolkit/high_level/manifest_building/manifests_create_tokens.rs
src/wrapped_radix_engine_toolkit/high_level/token_definition_metadata.rs

Fixes some issues introduced on https://github.com/radixdlt/sargon/pull/173, where the Transaction Manifest generated would be invalid due since some of the referred ids included in metadata weren't present on Stokenet.
[Here](https://stokenet-dashboard.radixdlt.com/resource/resource_tdx_2_1t4h3u5knhu308hfp5h6lwf7cq6pjl4wu0cvmjwjfy32hjfnzd745dj/metadata) is an example token built using these changes.

Fix Transaction Manifest builder

---

Cargo.lock
Cargo.toml
src/radix_connect/mobile/client.rs
src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/failure_response/failure.rs
src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/response.rs
src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/success.rs

This is a fix for the following bug:
- User performs the first connect to a dApp.
- User is presented with Origin verification screen.
- User goes back to the dApp and sends a another request. RDT will attach the same session_id.
- User is redirected to the Wallet.
- User dismisses the first request.
- When user tries to complete the second request and error will be thrown telling them that the session for the given session id was not found.
The above did happen because the session was saved to the storage only on success interaction, and it was immediately removed after user completed the interaction.
The fix for this is to have the per wallet_interaction_id session, so until a session is verified for a given session_id we can have multiple sessions in memory for different interactions.

Fix new sessions handling

---

Cargo.lock
Cargo.toml
apple/Tests/TestCases/Address/AccountAddressTests.swift
apple/Tests/TestCases/Address/LegacyOlympiaAccountAddressTests.swift
apple/Tests/TestCases/Prelude/NonFungibleGlobalIDTests.swift
jvm/sargon-android/src/test/java/com/radixdlt/sargon/NonFungibleGlobalIdTest.kt
src/profile/v100/address/account_address.rs
src/profile/v100/address/address_format.rs
src/profile/v100/address/legacy_olympia_account_address.rs
src/profile/v100/address/non_fungible_global_id.rs
src/profile/v100/address/non_fungible_local_id.rs
src/profile/v100/address/resource_address.rs
src/profile/v100/address/wrap_ret_address.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_hashes/transaction_hashes.rs

The `AddressFormat::Default` of the global id has changed according to the [Non-Fungible Display standard](https://docs.radixdlt.com/v1/docs/non-fungible-display#nonfungible-global-id-address-display).
In essence the default format for a global id will be as follows:
1. String: 
* RAW: `resource_sim1ngktvyeenvvqetnqwysevcx5fyvl6hqe36y3rkhdfdn6uzvt5366ha:<foobar>`
* DEFAULT:  `reso...5366ha:<foobar>`
2. Integer:
* RAW: `resource_sim1ngktvyeenvvqetnqwysevcx5fyvl6hqe36y3rkhdfdn6uzvt5366ha:#1#`
* DEFAULT:  `reso...5366ha:#1#`
3. Bytes:
* RAW: `resource_sim1ngktvyeenvvqetnqwysevcx5fyvl6hqe36y3rkhdfdn6uzvt5366ha:[dead]`
* DEFAULT:  `reso...5366ha:[dead]`
4. Ruid:
* RAW: `resource_sim1ngktvyeenvvqetnqwysevcx5fyvl6hqe36y3rkhdfdn6uzvt5366ha:{deadbeef12345678-babecafe87654321-fadedeaf01234567-ecadab …

Global id Default format

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Swiftified/Profile/AppPreferences+Swiftified.swift
apple/Tests/TestCases/Profile/AppPreferencesTests.swift
src/profile/v100/app_preferences/app_preferences.rs
src/profile/v100/app_preferences/app_preferences_uniffi_fn.rs
src/profile/v100/app_preferences/gateways/saved_gateways.rs

- When deserializing `SavedGateways`, if JSON has elements with same Url we will just skip those that are repeated.
- Add function to check if `AppPreferences` have a `Gateway` with the given `Url`.
Both changes should unlock this user and prevent having issues like this in the future. [JIRA](https://radixdlt.atlassian.net/browse/ABW-3500)

Skip duplicate Gateways without crashing

---

.github/workflows/release-android.yml
.github/workflows/release-desktop-bins.yml
jvm/buildSrc/src/main/java/com/radixdlt/cargo/toml/SargonVersion.kt

Maven libraries that are built from `workflow_dispatch` action will require a custom name. This is to differentiate them from the rest of the builds that come from CD. The reason is that when we build custom binaries for testing a branch rather than main the output used to be something like `1.0.23-2eb68d8c` which may be confused with a revision from main.
Resulting build names from workflow dispatch will look like this instead `1.0.23-custom-name-2eb68d8c` were the custom name will be required in the workflow dispatch context menu.

Set custom name to builds that come from workflow dispatch

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Methods/RET/ResourceSpecifier+Warp+Functions.swift
apple/Sources/Sargon/Extensions/SampleValues/RET/ResourceSpecifier+SampleValues.swift
apple/Sources/Sargon/Extensions/Swiftified/RET/ResourceSpecifier+Swiftified.swift
apple/Tests/TestCases/RET/ResourceSpecifierTests.swift
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/ResourceSpecifier.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/samples/ResourceSpecifierSample.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/ResourceSpecifierTest.kt
src/wrapped_radix_engine_toolkit/low_level/execution_summary/execution_summary.rs
src/wrapped_radix_engine_toolkit/low_level/execution_summary/mod.rs
src/wrapped_radix_engine_toolkit/low_level/execution_summary/resource_specifier/mod.rs
src/wrapped_radix_engine_toolkit/low_level/execution_summary/resource_specifier/resource_specifier.rs
src/wrapped_radix_engine_toolkit/low_level/execution_summary/resource_specifier/resource_specifier_uniffi.rs
src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/execution_summary/transaction_manifest_execution_summary.rs

Expose the full resource specifier, not just the address.

Properly expose transaction proofs

---

Cargo.lock
Cargo.toml
src/wallet/home_cards/manager.rs

This PR adds a `uniffi` exported function to notify the `HomeCardsManager` to clear the home cards both in-memory and from storage. This is required when factory resetting the wallet and ensures that all the control over the home cards is inside Sargon. Thanks, @matiasbzurovski for the suggestion.

Add function to clear home cards

---

Cargo.lock
Cargo.toml
src/wrapped_radix_engine_toolkit/high_level/manifest_building/third_party_deposit_update/third_party_deposits_delta.rs

Fixed the bug preventing from adding additional asset exception for the same rule.
Th old implementation was incorrectly checking only for the exception rule difference, ending in creating an empty manifest.
Original bug report: https://rdxworks.slack.com/archives/C03QFAWBRNX/p1721202200334219

Fix third party deposit asset exceptions

---

Cargo.lock
Cargo.toml
src/wallet/home_cards/manager.rs

Currently, whenever the wallet is restored there should be no home cards. 
The use case is as follows: 
The user clicks on a valid deep link -> installs the app -> the deep link is resolved -> home cards are saved to storage -> the user restores the wallet -> at this point we should ensure no home cards are stored.

Clear home cards after restore

---

Cargo.lock
Cargo.toml

Since I have had to set the tag 1.1.0 by hand the generated artefacts are not working. Re-trigger the whole deployment by bumping the version to 1.1.0

Bump to regenerate artefacts for iOS

---

Cargo.lock
Cargo.toml
apple/Sources/Sargon/Extensions/Methods/Prelude/FfiUrl+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Swiftified/Prelude/FfiUrl+Swiftified.swift
apple/Sources/Sargon/Extensions/Swiftified/Profile/AppPreferences+Swiftified.swift
apple/Tests/TestCases/Prelude/FfiUrlTests.swift
apple/Tests/TestCases/Profile/AppPreferencesTests.swift
src/lib.rs
src/profile/v100/app_preferences/app_preferences_uniffi_fn.rs
src/types/ffi_url.rs
src/types/mod.rs
src/types/uniffi_url.rs

Adds a wrapper around Rust `Url`, which has to be created on host sides. This way, if the conversion fails, the error is downcasted to host which will handle it appropiately (rather than having Rust code panic).

Add wrapper FfiUrl

---

Cargo.lock
Package.swift
crates/sargon/Cargo.toml

Update `AsyncExtensions` to version 0.5.3 to support Xcode 16.

Bump AsyncExtensions

---

apple/Sources/Sargon/SargonOS/SargonOS+Static+Shared.swift
apple/Sources/Sargon/SargonOS/TestOS.swift
apple/Sources/Sargon/Util/EventPublisher.swift
apple/Tests/IntegrationTests/DriversTests/DriversTests.swift
apple/Tests/IntegrationTests/DriversTests/InsecureStorageTests.swift
apple/Tests/IntegrationTests/SargonOS/SargonOSTests.swift
crates/sargon/src/profile/v100/header/mod.rs
crates/sargon/src/profile/v100/header/profile_id.rs
crates/sargon/src/profile/v100/header/profile_id_uniffi_fn.rs
crates/sargon/src/system/clients/client/secure_storage_client/secure_storage_client.rs
crates/sargon/src/system/drivers/secure_storage_driver/support/secure_storage_key.rs
crates/sargon/src/system/sargon_os/sargon_os_profile.rs
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/driver/AndroidStorageDriver.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/storage/key/ProfileSnapshotKeyMapping.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/SecureStorageKeyTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/key/ByteArrayKeyMappingTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/storage/key/ProfileSnapshotKeyMappingTest.kt

Add the profile id as part of ProfileSnapshot secure storage key. This is needed so the iOS wallet has the profile id when needing to save the profile data. It is meant to be ignored for other usages.

Profile snapshot id payload

---

jvm/gradle/libs.versions.toml
jvm/sargon-android/build.gradle.kts

Since there is no `sargon-desktop` module, there is no information for its dependencies. A dependency that needs to ship with sargon is the jna runtime. 
This can only be mitigated with adding a custom pom dependency for runtime jna.

Add JNA dependency to sargon-desktop-bins

---

crates/sargon/src/system/sargon_os/profile_state_holder.rs

Make use of [read](https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html#method.read) and [write](https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html#method.write) on the RWLock instead of [try_read](https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html#method.try_read) and [try_write](https://doc.rust-lang.org/stable/std/sync/struct.RwLock.html#method.try_write), which assure proper concurrent read/write access to the profile_state.

Profile safe concurrent access

---

Cargo.lock
crates/sargon/Cargo.toml
crates/sargon/src/wrapped_radix_engine_toolkit/low_level/execution_summary/new_entities.rs
crates/sargon/src/wrapped_radix_engine_toolkit/low_level/transaction_manifest/execution_summary/transaction_manifest_execution_summary.rs

`NewEntities` field will still include newly created resource addresses even if no metadata are present.

New entities metadata present when no metadata exist

---

Cargo.lock
crates/sargon/Cargo.toml
scripts/ios/release.sh

Trying to rid of the `Anka` author of our tags in our releases.
For more context see thread: https://rdxworks.slack.com/archives/C06EBEA0SGY/p1728481132742009?thread_ts=1728401660.134659&cid=C06EBEA0SGY

Git config author in release script

---

.gitignore
Cargo.toml
crates/sargon/src/types/samples/factor_source_ids_with_samples.rs

> [!NOTE]
> Target branch is not main, rather Ghenadies UniFFI branch
> We really want this change on main too, but we expect to merge the UniFFI sep branch soon
Make unit test run in 80% faster (On my Mac Studio, now rung in 40s instead of 75 sec).
The slow test run in 1.3 sec instead of 5.3 sec.
The culprit was the manual look up in `sample_associated_mnemonic` using `if ==` comparision, instead of using a map structure.
I profiled using [`flamegraph` which is a great tool](https://github.com/flamegraph-rs/flamegraph). It is a bit hard at first to understand. It is the width of the rows which matter, **not the color** nor does any horizintal position matter. 
See flramegraph file - this is run before this optimization
You need to boot your mac in Recovery Mode and disable SIP for …

make unit test run un-slow again.

---

Cargo.lock
crates/sargon/Cargo.toml
crates/sargon/src/system/drivers/networking_driver/support/test/mock_networking_driver.rs
crates/sargon/src/system/sargon_os/transactions/sargon_os_transaction_status.rs

Updates the Transaction status polling logic so that, if the endpoint response is a failure, we poll again after the corresponding delay. 
In other words, a failure response will now be considered as a successful response with `TransactionStatusResponsePayloadStatus::Unknown`. This is the behavior that host apps had before using Sargon to poll status.

Updates to Trancaction status polling

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/gateway_api/methods/transaction_methods.rs
crates/sargon/src/gateway_api/models/logic/request/transaction/preview/transaction_preview.rs
crates/sargon/src/system/sargon_os/transactions/sargon_os_transaction_analysis.rs
crates/sargon/src/wrapped_radix_engine_toolkit/low_level/v2/transaction_manifest_v2/subintent_manifest.rs

This is a temporary trick so we have properly working Enclosed Pre-Auth preview instead of a stubbed execution summary. We should replace with using the proper endpoint for v2 analysis when it is in place.

Use V1 analysis for enclosed manifests

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/pre_authorization/pre_authorization.rs
crates/sargon/Cargo.toml
crates/sargon/fixtures/vector/wallet_interactions_wallet_to_dapp.json
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/pre_authorization/mod.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/pre_authorization/pre_authorization.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/pre_authorization/subintent_response.rs
crates/sargon/tests/vectors/main.rs

Updates `WalletToDappInteractionPreAuthorizationResponseItems` to include one new layer (under `"resposne"` field) when sending back the `signedPartialTransaction`, as defined in [CAP-39](https://radixdlt.atlassian.net/wiki/spaces/AT/pages/3702816769/CAP-39+Pre-authorization+request#Wallet-response).

Update PreAuthorization response model

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/core/types/collections/identified_vec_of/identified_vec_of_modify.rs
crates/sargon/src/profile/v100/networks/network/authorized_dapp/authorized_dapp.rs
crates/sargon/src/profile/v100/networks/network/authorized_dapp/authorized_persona_simple.rs
crates/sargon/src/profile/v100/networks/network/authorized_dapp/shared_with_dapp.rs
crates/sargon/src/profile/v100/networks/network/authorized_dapps.rs
crates/sargon/src/profile/v100/networks/network/profile_network.rs
crates/sargon/src/profile/v100/networks/profile_networks.rs
crates/sargon/src/system/sargon_os/sargon_os_accounts.rs
crates/sargon/src/system/sargon_os/sargon_os_profile.rs

- Emit profile updates when an account is hidden/tombstoned.
- Remove account references from dApps when hidden/tombstoned.

Remove references to deleted accounts + emit profile changes

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/authorized_request.rs
crates/sargon-uniffi/src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/unauthorized_request.rs
crates/sargon-uniffi/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/authorized_request.rs
crates/sargon-uniffi/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/unauthorized_request.rs
crates/sargon/Cargo.toml
crates/sargon/fixtures/vector/wallet_interactions_dapp_to_wallet.json
crates/sargon/fixtures/vector/wallet_interactions_wallet_to_dapp.json
crates/sargon/src/radix_connect/mobile/deep_link_parsing/parser.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/authorized_request.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/dapp_to_wallet/interaction_items/request/unauthorized_request.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/authorized_request.rs
crates/sargon/src/radix_connect/wallet_interaction/dapp_wallet_interaction/wallet_to_dapp/success_response/unauthorized_request.rs
crates/sargon/tests/vectors/main.rs

This PR is essentially a "rearrangement" of the models from the previous [PR](https://github.com/radixdlt/sargon/pull/228). Specifically, it moves the proof of ownership to the authorized request. Relevant discussion [here](https://rdxworks.slack.com/archives/C07MXKW8659/p1729495704170929). 
[This is my first PR in Sargon](https://tenor.com/hBKAmPGW5BD.gif)!

[ABW-3037] Move proof of ownership data models from unauthorized request to authorized request

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/driver/AndroidBiometricAuthorizationDriver.kt

> [!note]
> Kotlin only change
In order for the secure storage driver to work with the android system and encrypt/decrypt data successfully, biometrics need to be provided. In order to ask for biometrics on Android, we need a reference to the activity/context that is currently visible in order to show the dialog for biometrics. 
This has already been handled by exposing a `BiometricsHandler` kotlin class that bridges this gap. Although the `askForBiometrics()` method was kept internal to the sargon kotlin library. There is real value to expose such method to host. The host can reuse the same mechanism and offload the biometrics authentication to `BiometricsHandler` improving the code on our view models.

Expose `askForBiometrics()` to host

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/system/sargon_os/sargon_os.rs
crates/sargon/src/system/sargon_os/sargon_os_factors.rs

I had accidentally missed some exucution paths in which we eagerly pre-derived FactorInstances for FactorSources. 
This PR gates pre-derivation behind `cfg(test)`. It is not possible for hosts to trigger prederivation. meaning passing `true` for `should_pre_derive_instances` to `new_wallet` is NOOP from hosts (I log a warning about it).

disable pre-derivation of factor sources in prod.

---

crates/sargon/src/signing/host_interaction/sign_request.rs
crates/sargon/src/signing/host_interaction/sign_response.rs
crates/sargon/src/signing/host_interaction/transaction_sign_request_input.rs
crates/sargon/src/signing/petition_types/petition_for_entity.rs
crates/sargon/src/signing/petition_types/petition_for_factors_types/petition_for_factors/petition_for_factors_state_snapshot.rs
crates/sargon/src/signing/signables/signable.rs
crates/sargon/src/signing/signatures_outecome_types/maybe_signed_transactions.rs
crates/sargon/src/signing/signatures_outecome_types/sign_with_factors_outcome.rs
crates/sargon/src/types/hd_signature.rs
crates/sargon/src/types/hd_signature_input.rs
crates/sargon/src/types/invalid_transaction_if_neglected.rs

we use:
```rust
impl<S: Signable + HasSampleValues> HasSampleValues for SignRequest<S>
where
S::Payload: HasSampleValues,
S::ID: HasSampleValues,
{
...
}
```
And in many more places

lift HasSampleValues restriction on Signable trait

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/driver/AndroidBiometricAuthorizationDriver.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/os/driver/AndroidStorageDriver.kt

This exception is needed to be `public` instead of `internal` so we can convert it back to common exception from host.
Specifically when using biometrics from host and want to return the error back to sargon (when using signing interactor), the ideal is to use the same error the secure storage driver would. That is why the `BiometricsFailure` is now public and the method inside `toCommonException` is public too.

Expose biometrics failure exception

---

Cargo.lock
apple/Sources/Sargon/SargonOS/ThrowingHostInteractor+Static+Shared.swift
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/core/error/common_error.rs
crates/sargon-uniffi/src/signing/authentication_signing_input.rs
crates/sargon-uniffi/src/signing/authentication_signing_request.rs
crates/sargon-uniffi/src/signing/authentication_signing_response.rs
crates/sargon-uniffi/src/signing/mod.rs
crates/sargon-uniffi/src/signing/rola_challenge.rs
crates/sargon-uniffi/src/system/interactors/host_interactor.rs
crates/sargon-uniffi/src/system/sargon_os/sargon_os_signing.rs
crates/sargon/Cargo.toml
crates/sargon/src/core/error/common_error.rs
crates/sargon/src/signing/authentication/authentication_signing_input.rs
crates/sargon/src/signing/authentication/authentication_signing_interactor.rs
crates/sargon/src/signing/authentication/rola_challenge.rs
crates/sargon/src/signing/testing/interactors/test_authentication_interactor.rs
crates/sargon/src/system/interactors/interactors.rs
crates/sargon/src/system/interactors/testing/test_use_factor_sources_interactors.rs
crates/sargon/src/system/interactors/use_factor_sources_interactor.rs
crates/sargon/src/system/sargon_os/sargon_os.rs
crates/sargon/src/system/sargon_os/sargon_os_signing.rs
jvm/sargon-android/src/main/java/com/radixdlt/sargon/extensions/RolaChallenge.kt
jvm/sargon-android/src/main/java/com/radixdlt/sargon/samples/RolaChallenge.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/RolaChallengeTest.kt
jvm/sargon-android/src/test/java/com/radixdlt/sargon/os/interactor/FakeHostInteractor.kt

Signing auth is used in login flows by the host. In similar fashion with `sign_transaction` and `sign_subintent`, `sign_auth` is exposed by sargon os. The `AuthenticationSigningInteractor` is added in `UseFactorSourcesInteractor`. Notable fact is that `RolaChallenge` also exposes the `hash` method used by host in order to sign it.

Expose sign auth

---

.pre-commit-config.yaml
Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/security_center/support/backup_result.rs
crates/sargon/Cargo.toml
crates/sargon/src/security_center/client.rs
crates/sargon/src/security_center/support/backup_result.rs

In this PR the unused `save_identifier` is removed from `BackupResult`. Related thread [here](https://rdxworks.slack.com/archives/C031A0V1A1W/p1733816964734079).
⚠️  This PR also removes the phylum from per-commit.

Remove save identifier from backup result

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/gateway_api/methods/state_methods.rs
crates/sargon/src/system/sargon_os/sargon_os_signing.rs

When implementing the delete account feature, we need to add in https://github.com/radixdlt/sargon/pull/268 special handling for 2 methods (`fetch_all_account_resource_preferences` & `fetch_all_account_authorized_depositors`) since their respective endpoints would return a `404` for virtual accounts. 
This was fixed by the Gateway team, so such handling is no longer necessary. This [integration test](https://github.com/radixdlt/sargon/blob/main/crates/sargon/src/system/sargon_os/delete_account/sargon_os_delete_account.rs#L373-L390) confirms it still works fine after the changes 🙂

Remove special handling for virtual accounts

---

Cargo.lock
apple/Sources/Sargon/Extensions/Methods/Profile/MFA/SecurityShieldBuilder+Wrap+Functions.swift
apple/Sources/Sargon/Extensions/Methods/SecurityCenter/SecurityProblemKind+Wrap+Functions.swift
apple/Tests/TestCases/Profile/MFA/SecurityShieldsBuilderTests.swift
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/profile/mfa/security_structures/mod.rs
crates/sargon-uniffi/src/profile/mfa/security_structures/security_shield_builder.rs
crates/sargon-uniffi/src/profile/mfa/security_structures/selected_factor_sources_status.rs
crates/sargon/Cargo.toml
crates/sargon/src/profile/mfa/security_structures/matrices/builder/matrix_builder.rs
crates/sargon/src/profile/mfa/security_structures/mod.rs
crates/sargon/src/profile/mfa/security_structures/security_shield_builder.rs
crates/sargon/src/profile/mfa/security_structures/selected_factor_sources_status.rs
crates/sargon/src/profile/v100/factors/factor_source_kind.rs

- Added `sorted_factor_sources_for_selection function`, which handles the logic for sorting a list of factor sources on the `Select Factors` screen.
- Added `selected_factor_sources_status` function, which returns a newly added enum, `SelectedFactorSourcesStatus`, representing the status of selected factor sources in the Security Shield building process.
- [Swift] Fixes the `allCases` for `SecurityProblemKind`

[ABW-3969] Shield Setup Select Factors - utility functions

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/signing/collector/extractor_of_instances_required_to_sign_transactions.rs
crates/sargon/src/signing/collector/signatures_collector.rs
crates/sargon/src/signing/extractor_of_entities_requiring_auth.rs
crates/sargon/src/system/sargon_os/sargon_os_signing.rs
crates/sargon/src/system/sargon_os/transactions/sargon_os_transaction_analysis.rs

Allow transaction manifests which contain unknown accounts which to require signatures. The Wallet should not reject such transactions.
References:
- https://rdxworks.slack.com/archives/C031A0V1A1W/p1734036514557019?thread_ts=1733976138.385129&cid=C031A0V1A1W
- https://rdxworks.slack.com/archives/C031A0V1A1W/p1734356845160559
The new behaviour was introduced with Sargon, and we reject the manifest at the moment we try to extract the public keys to be sent to the GW. Old implementation, did allow for unknown accounts, [see iOS for reference](https://github.com/radixdlt/babylon-wallet-ios/blob/4b0738caf583521751a5c03f3c6410ab956c68a3/RadixWallet/Clients/TransactionClient/TransactionClient%2BLive.swift#L50).

Transaction Analysis allow unknown accounts

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon/Cargo.toml
crates/sargon/src/core/error/common_error.rs
crates/sargon/src/lib.rs
crates/sargon/src/wrapped_radix_engine_toolkit/low_level/v1/transaction_manifest/instructions/instructions.rs
crates/sargon/src/wrapped_radix_engine_toolkit/low_level/v2/transaction_manifest_v2/instructions_v2/instructions_v2.rs

Propagate pretty diagnostics error for CompileError. This will help dApp developers to understand better the reason when a manifest is invalid.

Propagate compile diagnostics

---

Cargo.lock
apple/Sources/Sargon/Extensions/Swiftified/Profile/MFA/SecurityShieldBuilder+Swifified.swift
apple/Tests/TestCases/Profile/MFA/SecurityShieldsBuilderTests.swift
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/core/utils/builder_arc_map.rs
crates/sargon-uniffi/src/core/utils/mod.rs
crates/sargon-uniffi/src/profile/mfa/security_structures/security_shield_builder.rs
crates/sargon/Cargo.toml
crates/sargon/src/profile/mfa/security_structures/security_shield_builder.rs

To improve the handling of TCA state in the iOS host, we need to transform the UniFFI `SecurityShieldBuilder` to use value type semantics, similar to how the [TransactionBuilder is implemented in radix-engine-toolkit](https://github.com/radixdlt/radix-engine-toolkit/blob/2ab5b35a6cb96c9faeb98ed8df67b870336e6873/crates/radix-engine-toolkit-uniffi/src/builder/manifest_builder/builder_v1.rs#L24).
This change means that every mutating function will return a new instance of `SecurityShieldBuilder`.

Transform UniFFI SecurityShieldBuilder to value type semantics

---

Cargo.lock
crates/sargon-uniffi/Cargo.toml
crates/sargon-uniffi/src/signing/authentication/auth_intent.rs
crates/sargon/Cargo.toml
crates/sargon/src/signing/authentication/auth_intent.rs
crates/sargon/src/signing/authentication/auth_intent_hash.rs

AuthIntent needs to keep the origin string as received from the dApp and not change the contents of it. So instead of keeping it as a `Url`, it keeps track of a `DappOrigin` which is a wrapper around `String`.
The function `new_from_request` still performs a check of unwrapping a dApp origin into a Url to check if its validity, but the string is kept in `AuthIntent`. This string can be used in hosts to pass the request to ledger.

Replace url with dapp origin
